Sentiment Analysis LSTM

In [27]:
import nltk
import pandas as pd
from textblob import Word
from nltk.corpus import stopwords
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from keras.models import Sequential
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Dense, Embedding, LSTM, SpatialDropout1D
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical

In [18]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [19]:
data = pd.read_csv('/content/data.csv')

In [57]:
stop_words = stopwords.words('english')
data_cleaned = cleaning(data, stop_words)

In [58]:
data_cleaned.head()

Sentence Sentiment
0  geosolutions technology leverage benefon 's gp...  positive
1         $esi lows, $1.50 $2.50 bk real possibility  negative
2  last quarter 2010 , componenta 's net sale oub...  positive
3  accoring finnish-russian chamber commerce , ma...   neutral
4  sweish buyout firm sol remaining 22.4 percent ...   neutral

In [59]:
def cleaning(df, stop_words):
    df['Sentence'] = df['Sentence'].apply(lambda x: ' '.join(x.lower() for x in x.split()))

    df['Sentence'] = df['Sentence'].str.replace('d', '')

    df['Sentence'] = df['Sentence'].apply(lambda x: ' '.join(x for x in x.split() if x not in stop_words))

    df['Sentence'] = df['Sentence'].apply(lambda x: ' '.join([Word(x).lemmatize() for x in x.split()]))
    return df

In [60]:
tokenizer = Tokenizer(num_words=500, split=' ')
tokenizer.fit_on_texts(data_cleaned['Sentence'].values)
X = tokenizer.texts_to_sequences(data_cleaned['Sentence'].values)
X = pad_sequences(X)

In [61]:
model = Sequential()
model.add(Embedding(500, 120, input_length=X.shape[1]))
model.add(SpatialDropout1D(0.4))
model.add(LSTM(704, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(352, activation='LeakyReLU'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 51, 120)           60000     
                                                                 
 spatial_dropout1d_3 (Spati  (None, 51, 120)           0         
 alDropout1D)                                                    
                                                                 
 lstm_3 (LSTM)               (None, 704)               2323200   
                                                                 
 dense_6 (Dense)             (None, 352)               248160    
                                                                 
 dense_7 (Dense)             (None, 3)                 1059      
                                                                 
Total params: 2632419 (10.04 MB)
Trainable params: 2632419 (10.04 MB)
Non-trainable params: 0 (0.00 Byte)
______________

In [62]:
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(data_cleaned['Sentiment'])

In [63]:
num_classes = len(label_encoder.classes_)
y_onehot = to_categorical(y_encoded, num_classes=num_classes)

In [64]:
X_train, X_test, y_train_onehot, y_test_onehot = train_test_split(X, y_onehot, test_size=0.2, random_state=42)

In [65]:
model.fit(X_train, y_train_onehot, epochs=10, batch_size=32, verbose=1)

Epoch 1/10
147/147 [==============================] - 318s 2s/step - loss: 0.9326 - accuracy: 0.5707
Epoch 2/10
147/147 [==============================] - 297s 2s/step - loss: 0.7952 - accuracy: 0.6431
Epoch 3/10
147/147 [==============================] - 293s 2s/step - loss: 0.7147 - accuracy: 0.6865
Epoch 4/10
147/147 [==============================] - 316s 2s/step - loss: 0.6790 - accuracy: 0.6955
Epoch 5/10
147/147 [==============================] - 317s 2s/step - loss: 0.6518 - accuracy: 0.7098
Epoch 6/10
147/147 [==============================] - 314s 2s/step - loss: 0.6195 - accuracy: 0.7130
Epoch 7/10
147/147 [==============================] - 303s 2s/step - loss: 0.6031 - accuracy: 0.7239
Epoch 8/10
147/147 [==============================] - 289s 2s/step - loss: 0.5905 - accuracy: 0.7289
Epoch 9/10
147/147 [==============================] - 290s 2s/step - loss: 0.5669 - accuracy: 0.7391
Epoch 10/10
147/147 [==============================] - 288s 2s/step - loss: 0.5495 - accura

In [66]:
test_loss, test_accuracy = model.evaluate(X_test, y_test_onehot)
print(f'Test Loss: {test_loss}')
print(f'Test Accuracy: {test_accuracy}')

37/37 [==============================] - 13s 352ms/step - loss: 0.8612 - accuracy: 0.6476
Test Loss: 0.8612058162689209
Test Accuracy: 0.6475620269775391


Programming for sentiment analysis problem:
Given a text, classify it into categories: positive, negative, neutral.
Requirements:
1) Use different text representations: binary mode, count mode, tf.idf mode.
2) Use 1-gram and 2-gram features
3) Use different machine learning methods: SVM, logistic regression, Decision Tree, Random Forest

There are many datasets on the Internet that can be used.
Can work on Vietnamese or English data

In [74]:
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
from textblob import Word
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from nltk import download
from nltk import word_tokenize

In [68]:
download('punkt')
download('stopwords')
download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [69]:
data = pd.read_csv('/content/data.csv')


In [70]:
def cleaning(df):
    stop_words = set(stopwords.words('english'))
    df['cleaned'] = df['Sentence'].apply(lambda x: ' '.join(x.lower() for x in x.split()))
    df['cleaned'] = df['cleaned'].str.replace('\d+', '')
    df['cleaned'] = df['cleaned'].apply(lambda x: ' '.join(x for x in x.split() if x not in stop_words))
    df['cleaned'] = df['cleaned'].apply(lambda x: ' '.join([Word(word).lemmatize() for word in word_tokenize(x)]))
    return df

data_cleaned = cleaning(data)


<ipython-input-70-2f2c3e92de2f>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df['cleaned'] = df['cleaned'].str.replace('\d+', '')


In [75]:
# Vectorization
vectorizers = {
    'Binary': CountVectorizer(binary=True, ngram_range=(1, 2)),
    'Count': CountVectorizer(ngram_range=(1, 2)),
    'TF-IDF': TfidfVectorizer(ngram_range=(1, 2))
}


In [71]:
# Models
models = {
    'Logistic Regression': LogisticRegression(max_iter=100),
    'SVM': SVC(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier()
}


In [72]:
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(data_cleaned['Sentiment'])


In [ ]:
for name, vectorizer in vectorizers.items():
    X_vectorized = vectorizer.fit_transform(data_cleaned['cleaned']).toarray()


    X_train, X_test, y_train, y_test = train_test_split(X_vectorized, y_encoded, test_size=0.2, random_state=42)

    print(f"Using {name} Vectorization\n")

    for model_name, model in models.items():
        model.fit(X_train, y_train)
        predictions = model.predict(X_test)

        print(f"{model_name} Classification Report:")
        print(classification_report(y_test, predictions))
        print("Confusion Matrix:")
        print(confusion_matrix(y_test, predictions))
        print(f"Accuracy: {accuracy_score(y_test, predictions)}\n")

Using Binary Vectorization



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Logistic Regression Classification Report:
              precision    recall  f1-score   support

           0       0.27      0.18      0.21       175
           1       0.70      0.82      0.76       622
           2       0.78      0.68      0.73       372

    accuracy                           0.68      1169
   macro avg       0.58      0.56      0.57      1169
weighted avg       0.66      0.68      0.67      1169

Confusion Matrix:
[[ 31 107  37]
 [ 77 512  33]
 [  7 113 252]]
Accuracy: 0.6800684345594525

SVM Classification Report:
              precision    recall  f1-score   support

           0       0.22      0.05      0.08       175
           1       0.64      0.94      0.76       622
           2       0.81      0.49      0.61       372

    accuracy                           0.66      1169
   macro avg       0.56      0.49      0.48      1169
weighted avg       0.63      0.66      0.61      1169

Confusion Matrix:
[[  8 134  33]
 [ 28 583  11]
 [  0 190 182]]
Accuracy: 

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Logistic Regression Classification Report:
              precision    recall  f1-score   support

           0       0.27      0.17      0.21       175
           1       0.70      0.82      0.75       622
           2       0.78      0.68      0.72       372

    accuracy                           0.68      1169
   macro avg       0.58      0.56      0.56      1169
weighted avg       0.66      0.68      0.66      1169

Confusion Matrix:
[[ 30 108  37]
 [ 75 511  36]
 [  7 113 252]]
Accuracy: 0.6783575705731394

SVM Classification Report:
              precision    recall  f1-score   support

           0       0.26      0.05      0.09       175
           1       0.64      0.94      0.76       622
           2       0.80      0.47      0.59       372

    accuracy                           0.66      1169
   macro avg       0.57      0.49      0.48      1169
weighted avg       0.63      0.66      0.61      1169

Confusion Matrix:
[[  9 132  34]
 [ 25 586  11]
 [  0 196 176]]
Accuracy: 